version: 0.2

env:
  shell: bash

phases:
  pre_build:
    on-failure: ABORT
    commands:
      - export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain breezeware --domain-owner 305251478828 --query authorizationToken --output text`
      - mvn clean -s mvn-settings.xml validate
      - mvn clean -s mvn-settings.xml compile
  build:
    commands:
      - mvn clean -s mvn-settings.xml install
      - mvn clean -s mvn-settings.xml package
  post_build:
    commands:
      - |
        if [[ $CODEBUILD_BUILD_SUCCEEDING -eq 0 ]]
        then
            exit 1
        fi
      - mvn clean -s mvn-settings.xml site
      - mvn clean -s mvn-settings.xml deploy
cache:
  paths:
    - '/root/.m2/**/*'
