services:
  dynamo-health-showcase-api-server:
    image: 305251478828.dkr.ecr.us-east-1.amazonaws.com/api-app:latest
    container_name: dynamo-health-showcase-api-server
    ports:
      - "8443:8443"
    depends_on:
      health-db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8443/actuator/health" ]
      interval: 30s
      timeout: 7s
      retries: 4
      start_period: 60s
    env_file:
      - .env.dynamo-health
    restart: no
    networks:
      - dynamo-health-platform

  health-db:
    image: postgres:12.1
    container_name: dynamo-health-db
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 7s
      start_period: 2s
      retries: 3
    environment:
      POSTGRES_DB: dynamo_health_db
      POSTGRES_USER: dynamo_health_usr
      POSTGRES_PASSWORD: dynamohealth123
    restart: "no"
    volumes:
      - dynamo-health-showcase-restful-server-data:/app/data
    networks:
      - dynamo-health-platform
  #  Patient Web
  dynamo-health-patient-web:
    build:
      context: ../frontend/dynamo-health-patient-app
    container_name: dynamo-health-patient-app
    env_file: .env.dynamo-health
    ports:
      - "3000:80"
    restart: no
    networks:
      - dynamo-health-platform
  #  Care team Web
  dynamo-health-careteam-web:
    build:
      context: ../frontend/dynamo-health-careteam-app
    container_name: dynamo-health-careteam-app
    env_file: .env.dynamo-health
    ports:
      - "3001:80"
    restart: no
    networks:
      - dynamo-health-platform
  #  Provider Web
  dynamo-health-provider-web:
    build:
      context: ../frontend/dynamo-health-provider-app
    container_name: dynamo-health-provider-app
    env_file: .env.dynamo-health
    ports:
      - "3002:80"
    restart: no
    networks:
      - dynamo-health-platform


volumes:
  dynamo-health-showcase-restful-server-data:

networks:
  dynamo-health-platform:
