services:
  dynamo-backend:
    image: 305251478828.dkr.ecr.us-east-1.amazonaws.com/dynamo-showcase-app:latest
    container_name: dynamo-backend
    ports:
      - "8080:8443"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8443/actuator/health"]
      interval: 30s
      timeout: 7s
      start_period: 60s
      retries: 5
    env_file: .env.docker-compose.development
    restart: "no"
    networks:
      - dynamo-platform

  db:
    image: dynamo-db:latest
    container_name: dynamo-db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 7s
      start_period: 2s
      retries: 3
    environment:
      POSTGRES_DB: dynamo_db
      PGDATA: /var/lib/postgresql/data/dynamo
    restart: "no"
    volumes:
      - dynamo-restful-server-data:/app/data
    networks:
      - dynamo-platform

  dynamo-web-ui:
    image: dynamo-web-ui:latest
    container_name: dynamo-web-ui
    ports:
      - "3000:80"
    restart: no
    networks:
      - dynamo-platform

volumes:
  dynamo-restful-server-data:

networks:
  dynamo-platform:
